#**Importing Necessary Libraries**

In [ ]:


import numpy as np
import pandas as pd

#**Loading the Birds Dataset**

There are many kinds of birds: pigeons, ducks, ostriches, penguins… Some are good at flying, others can't fly but run fast. Some swim under water, others wading in shallow pool.

According to their living environments and living habits, birds are classified into different ecological groups. There are 6 ecological groups of birds:

* Swimming Birds (SW)
* Wading Birds (W)
* Terrestrial Birds (T)
* Raptors (R)
* Scansorial Birds (P)
* Singing Birds (SO)

Apparently, birds belong to different ecological groups have different appearances: **flying birds have strong wings and wading birds have long legs**. Their living habits are somewhat reflected in their bones' shapes. As data scientists we may think of examining the underlying relationship between sizes of bones and ecological groups, and recognising birds' ecological groups by their bones' shapes.

![An image](https://animalcorner.org/wp-content/uploads/2015/04/bird_skeleton1.jpg)

**Content**

There are 420 birds contained in this dataset. Each bird is represented by 10 measurements (features):

* Length and Diameter of Humerus
* Length and Diameter of Ulna
* Length and Diameter of Femur
* Length and Diameter of Tibiotarsus
* Length and Diameter of Tarsometatarsus

In [22]:
bird_data = pd.read_csv('bird.csv',delimiter = ',') #('/content/drive/MyDrive/AMITY/STUDENT_BOOTCAMP/Data/bird.csv', delimiter = ',')
bird_data.head(5)

id   huml  humw  ulnal  ulnaw   feml  femw   tibl  tibw   tarl  tarw type
0   0  80.78  6.68  72.01   4.88  41.81  3.70   5.50  4.03  38.70  3.84   SW
1   1  88.91  6.63  80.53   5.59  47.04  4.30  80.22  4.51  41.50  4.01   SW
2   2  79.97  6.37  69.26   5.28  43.07  3.90  75.35  4.04  38.31  3.34   SW
3   3  77.65  5.70  65.76   4.77  40.04  3.52  69.17  3.40  35.78  3.41   SW
4   4  62.80  4.84  52.09   3.73  33.95  2.72  56.27  2.96  31.88  3.13   SW

#**Accessing the Column Names in the Dataset**

In [23]:
bird_data.columns

Index(['id', 'huml', 'humw', 'ulnal', 'ulnaw', 'feml', 'femw', 'tibl', 'tibw',
       'tarl', 'tarw', 'type'],
      dtype='object')

In [24]:
bird_data = bird_data.set_index('id')
bird_data.head()

huml  humw  ulnal  ulnaw   feml  femw   tibl  tibw   tarl  tarw type
id                                                                       
0   80.78  6.68  72.01   4.88  41.81  3.70   5.50  4.03  38.70  3.84   SW
1   88.91  6.63  80.53   5.59  47.04  4.30  80.22  4.51  41.50  4.01   SW
2   79.97  6.37  69.26   5.28  43.07  3.90  75.35  4.04  38.31  3.34   SW
3   77.65  5.70  65.76   4.77  40.04  3.52  69.17  3.40  35.78  3.41   SW
4   62.80  4.84  52.09   3.73  33.95  2.72  56.27  2.96  31.88  3.13   SW

#**Finding the Shape of the Dataset**

In [25]:
bird_data.shape

(420, 11)

In [26]:
bird_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 420 entries, 0 to 419
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   huml    419 non-null    float64
 1   humw    419 non-null    float64
 2   ulnal   417 non-null    float64
 3   ulnaw   418 non-null    float64
 4   feml    418 non-null    float64
 5   femw    419 non-null    float64
 6   tibl    418 non-null    float64
 7   tibw    419 non-null    float64
 8   tarl    419 non-null    float64
 9   tarw    419 non-null    float64
 10  type    420 non-null    object 
dtypes: float64(10), object(1)
memory usage: 39.4+ KB


#**Checking Missing Values**

In [27]:
bird_data.isna().sum()

huml     1
humw     1
ulnal    3
ulnaw    2
feml     2
femw     1
tibl     2
tibw     1
tarl     1
tarw     1
type     0
dtype: int64

In [28]:
bird_data.dropna(how='any', inplace=True)

In [29]:
bird_data.isna().sum()

huml     0
humw     0
ulnal    0
ulnaw    0
feml     0
femw     0
tibl     0
tibw     0
tarl     0
tarw     0
type     0
dtype: int64

In [30]:
bird_data.shape

(413, 11)

# **Unique Values in the Data**

In [31]:
bird_data.nunique()

huml     403
humw     319
ulnal    394
ulnaw    305
feml     397
femw     287
tibl     401
tibw     283
tarl     403
tarw     277
type       6
dtype: int64

In [32]:
bird_data['type'].unique()

array(['SW', 'W', 'T', 'R', 'P', 'SO'], dtype=object)

# **Label Encoding of Categorical Variables**

Label Encoding means converting categorical features into numerical values. So that they can be fitted by machine learning models which only take numerical data.

**Example:**
Suppose we have a column Height in some dataset that has elements as Tall, Medium, and short. To convert this categorical column into a numerical column we will apply label encoding to this column. After applying label encoding, the Height column is converted into a numerical column having elements 0,1, and 2 where 0 is the label for tall, 1 is the label for medium, and 2 is the label for short height.

In [33]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
bird_data[['type']] = bird_data[['type']].apply(le.fit_transform)

In [34]:
bird_data.head()

huml  humw  ulnal  ulnaw   feml  femw   tibl  tibw   tarl  tarw  type
id                                                                        
0   80.78  6.68  72.01   4.88  41.81  3.70   5.50  4.03  38.70  3.84     3
1   88.91  6.63  80.53   5.59  47.04  4.30  80.22  4.51  41.50  4.01     3
2   79.97  6.37  69.26   5.28  43.07  3.90  75.35  4.04  38.31  3.34     3
3   77.65  5.70  65.76   4.77  40.04  3.52  69.17  3.40  35.78  3.41     3
4   62.80  4.84  52.09   3.73  33.95  2.72  56.27  2.96  31.88  3.13     3

#**Seperating Label from Data**

In [35]:
y = bird_data['type']
X = bird_data.drop(['type'],axis=1)

In [36]:
X.columns

Index(['huml', 'humw', 'ulnal', 'ulnaw', 'feml', 'femw', 'tibl', 'tibw',
       'tarl', 'tarw'],
      dtype='object')

In [37]:
X.shape

(413, 10)

In [38]:
y

id
0      3
1      3
2      3
3      3
4      3
      ..
415    2
416    2
417    2
418    2
419    2
Name: type, Length: 413, dtype: int64

In [39]:
y.shape

(413,)

#**One-Hot-Encoding**

* It allows the use of categorical variables in models that require numerical input.
* It can improve model performance by providing more information to the model about the categorical variable.
* It can help to avoid the problem of ordinality, which can occur when a categorical variable has a natural ordering (e.g. “small”, “medium”, “large”).

In [40]:
from keras.utils import to_categorical
num_classes = 6
y = to_categorical(y, num_classes)
y

array([[0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       ...,
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]], dtype=float32)

#**Splitting the Data into Training and Testing**

In [41]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 2)

In [42]:
print("Shape of the X_train", X_train.shape)
print("Shape of the X_test", X_test.shape)
print("Shape of the y_train", y_train.shape)
print("Shape of the y_test", y_test.shape)

Shape of the X_train (289, 10)
Shape of the X_test (124, 10)
Shape of the y_train (289, 6)
Shape of the y_test (124, 6)


# **Feature Scaling:**
The result of **standardization** (or **Z-Score normalization**) is that the features will be re scaled so that they'll have the properties of a standard normal distribution with:
$$\mu = 0$$
And
$$\sigma = 1$$

Where $\mu$ is the mean(average) and $\sigma$ is the standard deviation from the mean; standard scores (also called **Z** scores) of the sampels are calculated as follows:
$$z = \frac{x - \mu}{\sigma}$$

***

# **About Min-Max Scaling**

An alternative approach to **Z-Score** normalization (or called standardization) is the so-called **Min-Max Scaling** (often also simply called **Normalization** - a common cause for ambiguities)

In this approach, the data is scaled to a fixed range - usually `[0, 1]`.
The cost of having this bounded range - in contrast to standrdization - is that we will end up with smaaller standard deviations, which can suppress the effect of outliers.

**Note**:

If the dataset have lot's of outliers, and the algorithms are sensitive to outliers, please use `Min-Max Scaler`

A `Min-Max Scaling` is typically done via the foloowing equation:

$$X_{norm} = \frac{X_{i} - X_{min}}{X_{max} - X_{min}}$$

$X_i$ is the $i^{th}$ sample of dataset.


# **Z-Score Standardization or Min-Max Scaling**

"Standardization or Min-Max scaling"? - There is no obvious answer to this question: it really depends on the application.

However this doesn't mean that `Min-Max Scaling` is not useful at all, A popular application is `image processing`, where pixel intensities have to be normalized to fit withint a certain range (i.e., `[0, 255]` for the RGB colour range). Also, typical _Neural Network_ Algorithm require data that on a `0 - 1` scale.

In [43]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

#**Building the ANN Model**

In [44]:
# sequential model to initialise our ann and dense module to build the layers
from keras.models import Sequential
from keras.layers import Dense

In [45]:
classifier = Sequential()
# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 8, kernel_initializer = 'uniform', activation = 'relu', input_dim = 10))

# Adding the second hidden layer
classifier.add(Dense(units = 16, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the third hidden layer
classifier.add(Dense(units = 32, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'softmax'))

2024-01-05 10:34:00.776907: E tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected


# **Compiling and Fitting the Model**

In [50]:
classifier.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 16, epochs = 100, verbose = 3)

Epoch 1/100
Epoch 2/100
Epoch 3/100
Epoch 4/100
Epoch 5/100
Epoch 6/100
Epoch 7/100
Epoch 8/100
Epoch 9/100
Epoch 10/100
Epoch 11/100
Epoch 12/100
Epoch 13/100
Epoch 14/100
Epoch 15/100
Epoch 16/100
Epoch 17/100
Epoch 18/100
Epoch 19/100
Epoch 20/100
Epoch 21/100
Epoch 22/100
Epoch 23/100
Epoch 24/100
Epoch 25/100
Epoch 26/100
Epoch 27/100
Epoch 28/100
Epoch 29/100
Epoch 30/100
Epoch 31/100
Epoch 32/100
Epoch 33/100
Epoch 34/100
Epoch 35/100
Epoch 36/100
Epoch 37/100
Epoch 38/100
Epoch 39/100
Epoch 40/100
Epoch 41/100
Epoch 42/100
Epoch 43/100
Epoch 44/100
Epoch 45/100
Epoch 46/100
Epoch 47/100
Epoch 48/100
Epoch 49/100
Epoch 50/100
Epoch 51/100
Epoch 52/100
Epoch 53/100
Epoch 54/100
Epoch 55/100
Epoch 56/100
Epoch 57/100
Epoch 58/100
Epoch 59/100
Epoch 60/100
Epoch 61/100
Epoch 62/100
Epoch 63/100
Epoch 64/100
Epoch 65/100
Epoch 66/100
Epoch 67/100
Epoch 68/100
Epoch 69/100
Epoch 70/100
Epoch 71/100
Epoch 72/100
Epoch 73/100
Epoch 74/100
Epoch 75/100
Epoch 76/100
Epoch 77/100
Epoch 78

#**Testing the Model**

In [47]:
score, acc = classifier.evaluate(X_train, y_train,
                            batch_size=10)
print('Train score:', score)
print('Train accuracy:', acc)

print('*'*20)
score, acc = classifier.evaluate(X_test, y_test,
                            batch_size=10)
print('Test score:', score)
print('Test accuracy:', acc)

29/29 [==============================] - 0s 656us/step - loss: 0.2465 - accuracy: 0.8997
Train score: 0.24649691581726074
Train accuracy: 0.899653971195221
********************
13/13 [==============================] - 0s 755us/step - loss: 0.8509 - accuracy: 0.8548
Test score: 0.8508892059326172
Test accuracy: 0.8548387289047241


#**Confusion Matrix**

### * **Accuracy**
number of examples correctly predicted / total number of examples  
![alt text](https://wikimedia.org/api/rest_v1/media/math/render/svg/c72ec21ef2505c2d376e96197637fc64f75e5891)

In [46]:
# Predicting the Test set results
pred = classifier.predict(X_test)
print("Y_pred:", pred)
print("*****************")
y_pred = np.argmax(pred, axis = 1)
print("Y_pred:", y_pred)
print("*****************")
print("Y_test:", y_test)
y_true = np.argmax(y_test, axis = 1)
print("*****************")
print("Y_test:", y_true)

4/4 [==============================] - 0s 2ms/step
Y_pred: [[0.16666801 0.1666678  0.16666539 0.16666618 0.16666596 0.16666667]
 [0.16667575 0.16666801 0.16665715 0.16665317 0.16667552 0.16667038]
 [0.16666912 0.16666865 0.16666278 0.16666687 0.16666564 0.16666692]
 [0.16667117 0.16667023 0.16666281 0.16666345 0.1666641  0.16666819]
 [0.16666918 0.16666919 0.16666394 0.16666509 0.16666505 0.16666757]
 [0.16667344 0.16667019 0.16665769 0.16666299 0.16667053 0.16666515]
 [0.16666763 0.16667171 0.1666627  0.16665827 0.16667172 0.16666797]
 [0.16667041 0.16667001 0.1666633  0.16666403 0.16666421 0.16666806]
 [0.16667345 0.16667931 0.16665538 0.16666085 0.1666702  0.16666086]
 [0.16667509 0.16667329 0.16665383 0.16666223 0.16667183 0.1666637 ]
 [0.16667047 0.1666699  0.16666327 0.16666396 0.16666439 0.16666798]
 [0.16666861 0.16666861 0.16666372 0.16666596 0.16666572 0.16666739]
 [0.16666965 0.16666855 0.16666217 0.16666597 0.16666801 0.16666563]
 [0.1666687  0.16666865 0.16666485 0.1666653

2024-01-03 09:25:12.914699: I tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:655] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.


In [47]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_true, y_pred)
target_names = ['P', 'R', 'SO', 'SW', 'T', 'W']

ValueError: Classification metrics can't handle a mix of multiclass-multioutput and multiclass targets

In [51]:
import matplotlib.pyplot as plt
import seaborn as sns

ModuleNotFoundError: No module named 'matplotlib'

In [ ]:
p = sns.heatmap(pd.DataFrame(cm), annot=True,xticklabels=target_names, yticklabels=target_names, cmap="YlGnBu" ,fmt='g')
plt.title('Confusion matrix', y=1.1)
plt.ylabel('Actual label')
plt.xlabel('Predicted label')

#**Classification Report**
#**Classification Report**

### * **True Positive Rate**
number of samples actually and predicted as  `Positive` / total number of samples actually `Positive`  
Also called **Sensitivity or Recall**.  
![alt text](https://wikimedia.org/api/rest_v1/media/math/render/svg/64d5540cbadeb83f864d7a731b7ab43cccd0f353)


### * **Positive Predictive Value**
number of samples actually and predicted as  `Positive` / total number of samples predicted as `Positive`  
Also called **Precision**.  
![alt text](https://wikimedia.org/api/rest_v1/media/math/render/svg/699fcdb880b7f6a92742bc0845b8b60b59806a98)

### * **F1 score**
Harmonic Mean of Precision and Recall.  
![alt text](https://wikimedia.org/api/rest_v1/media/math/render/svg/5663ca95d471868169c4e4ea57c936f1b6f4a588)

In [52]:
#import classification_report
from sklearn.metrics import classification_report
print(classification_report(y_true,y_pred, target_names = target_names))

NameError: name 'y_true' is not defined

#**ROC curve**

In [53]:
from sklearn.metrics import roc_curve, auc
from itertools import cycle
fpr = dict()
tpr = dict()
roc_auc = dict()
for i in range(6):
    fpr[i], tpr[i], _ = roc_curve(y_test[:, i], pred[:, i])
    roc_auc[i] = auc(fpr[i], tpr[i])

# Plot of a ROC curve for a specific class
for i in range(6):
    plt.figure()
    plt.plot(fpr[i], tpr[i], label='ROC curve (area = %0.2f)' % roc_auc[i])
    plt.plot([0, 1], [0, 1], 'k--')
    plt.xlim([0.0, 1.0])
    plt.ylim([0.0, 1.05])
    plt.xlabel('False Positive Rate')
    plt.ylabel('True Positive Rate')
    plt.title('Receiver operating characteristic example')
    plt.legend(loc="lower right")
    plt.show()

NameError: name 'pred' is not defined

In [54]:
fpr = dict()
tpr = dict()
roc_auc = dict()
lw=2
for i in range(6):
    fpr[i], tpr[i], _ = roc_curve(y_test[:, i], pred[:, i])
    roc_auc[i] = auc(fpr[i], tpr[i])
colors =cycle(['blue', 'green', 'red','darkorange','olive','purple'])
for i, color in zip(range(6), colors):
    plt.plot(fpr[i], tpr[i], color=color, lw=2,
             label='AUC = {1:0.4f}'
             ''.format(i, roc_auc[i]))
plt.plot([0, 1], [0, 1], 'k--', lw=lw)
plt.xlim([-0.05, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate',fontsize=15)
plt.ylabel('True Positive Rate',fontsize=15)
# plt.title('Receiver operating characteristic for multi-class data')
plt.legend(loc="lower right")
plt.show()

NameError: name 'pred' is not defined

# **Finetuing the Network**

In [ ]:
# Tuning the ANN
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense
def build_classifier(optimizer):
    classifier = Sequential()
    classifier.add(Dense(units = 8, kernel_initializer = 'uniform', activation = 'relu', input_dim = 10))
    classifier.add(Dense(units = 16, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 32, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = optimizer, loss = 'categorical_crossentropy', metrics = ['accuracy'])
    return classifier
classifier = KerasClassifier(build_fn = build_classifier)
parameters = {'batch_size': [16, 32],
              'epochs': [800, 1000],
              'optimizer': ['adam', 'rmsprop']}
grid_search = GridSearchCV(estimator = classifier,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10)
grid_search = grid_search.fit(X_train, y_train,verbose = 1)
best_parameters = grid_search.best_params_
best_accuracy = grid_search.best_score_

Epoch 1/800


/tmp/ipykernel_2942/1183103113.py:14: DeprecationWarning: KerasClassifier is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead. See https://www.adriangb.com/scikeras/stable/migration.html for help migrating.
  classifier = KerasClassifier(build_fn = build_classifier)


17/17 [==============================] - 1s 1ms/step - loss: 1.7882 - accuracy: 0.2731
Epoch 2/800
17/17 [==============================] - 0s 886us/step - loss: 1.7779 - accuracy: 0.3038
Epoch 3/800
17/17 [==============================] - 0s 890us/step - loss: 1.7593 - accuracy: 0.3038
Epoch 4/800
17/17 [==============================] - 0s 893us/step - loss: 1.7155 - accuracy: 0.3462
Epoch 5/800
17/17 [==============================] - 0s 876us/step - loss: 1.6384 - accuracy: 0.5308
Epoch 6/800
17/17 [==============================] - 0s 865us/step - loss: 1.5821 - accuracy: 0.5231
Epoch 7/800
17/17 [==============================] - 0s 821us/step - loss: 1.5150 - accuracy: 0.5231
Epoch 8/800
17/17 [==============================] - 0s 825us/step - loss: 1.4558 - accuracy: 0.5154
Epoch 9/800
17/17 [==============================] - 0s 824us/step - loss: 1.3910 - accuracy: 0.5231
Epoch 10/800
17/17 [==============================] - 0s 824us/step - loss: 1.3415 - accuracy: 0.5231
Epo

/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:776: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py", line 767, in _score
    scores = scorer(estimator, X_test, y_test)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py", line 220, in __call__
    return self._score(
  File "/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py", line 268, in _score
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py", line 192, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py", line 221, in accuracy_score
    y_type, y_true, y_pred = _check_targets(y_true, y_pred)
 

17/17 [==============================] - 1s 1ms/step - loss: 1.7888 - accuracy: 0.2462
Epoch 2/800
17/17 [==============================] - 0s 948us/step - loss: 1.7794 - accuracy: 0.2923
Epoch 3/800
17/17 [==============================] - 0s 963us/step - loss: 1.7597 - accuracy: 0.2923
Epoch 4/800
17/17 [==============================] - 0s 943us/step - loss: 1.7103 - accuracy: 0.3423
Epoch 5/800
17/17 [==============================] - 0s 994us/step - loss: 1.6333 - accuracy: 0.5269
Epoch 6/800
17/17 [==============================] - 0s 913us/step - loss: 1.5404 - accuracy: 0.5038
Epoch 7/800
17/17 [==============================] - 0s 813us/step - loss: 1.4803 - accuracy: 0.4962
Epoch 8/800
17/17 [==============================] - 0s 747us/step - loss: 1.4172 - accuracy: 0.5115
Epoch 9/800
17/17 [==============================] - 0s 796us/step - loss: 1.3648 - accuracy: 0.5154
Epoch 10/800
17/17 [==============================] - 0s 813us/step - loss: 1.3300 - accuracy: 0.5231
Epo

/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:776: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py", line 767, in _score
    scores = scorer(estimator, X_test, y_test)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py", line 220, in __call__
    return self._score(
  File "/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py", line 268, in _score
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py", line 192, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py", line 221, in accuracy_score
    y_type, y_true, y_pred = _check_targets(y_true, y_pred)
 

17/17 [==============================] - 1s 1ms/step - loss: 1.7883 - accuracy: 0.3000
Epoch 2/800
17/17 [==============================] - 0s 938us/step - loss: 1.7774 - accuracy: 0.3000
Epoch 3/800
17/17 [==============================] - 0s 885us/step - loss: 1.7555 - accuracy: 0.3000
Epoch 4/800
17/17 [==============================] - 0s 903us/step - loss: 1.7112 - accuracy: 0.3462
Epoch 5/800
17/17 [==============================] - 0s 885us/step - loss: 1.6191 - accuracy: 0.4038
Epoch 6/800
17/17 [==============================] - 0s 842us/step - loss: 1.5388 - accuracy: 0.4462
Epoch 7/800
17/17 [==============================] - 0s 761us/step - loss: 1.4776 - accuracy: 0.4923
Epoch 8/800
17/17 [==============================] - 0s 753us/step - loss: 1.4185 - accuracy: 0.5038
Epoch 9/800
17/17 [==============================] - 0s 755us/step - loss: 1.3694 - accuracy: 0.5154
Epoch 10/800
17/17 [==============================] - 0s 736us/step - loss: 1.3299 - accuracy: 0.5154
Epo

/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:776: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py", line 767, in _score
    scores = scorer(estimator, X_test, y_test)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py", line 220, in __call__
    return self._score(
  File "/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py", line 268, in _score
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py", line 192, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py", line 221, in accuracy_score
    y_type, y_true, y_pred = _check_targets(y_true, y_pred)
 

17/17 [==============================] - 1s 1ms/step - loss: 1.7888 - accuracy: 0.2615
Epoch 2/800
17/17 [==============================] - 0s 1ms/step - loss: 1.7784 - accuracy: 0.2962
Epoch 3/800
17/17 [==============================] - 0s 1ms/step - loss: 1.7592 - accuracy: 0.2962
Epoch 4/800
17/17 [==============================] - 0s 1ms/step - loss: 1.7081 - accuracy: 0.2962
Epoch 5/800
17/17 [==============================] - 0s 1ms/step - loss: 1.6356 - accuracy: 0.2962
Epoch 6/800
17/17 [==============================] - 0s 871us/step - loss: 1.5749 - accuracy: 0.3654
Epoch 7/800
17/17 [==============================] - 0s 816us/step - loss: 1.5213 - accuracy: 0.5115
Epoch 8/800
17/17 [==============================] - 0s 836us/step - loss: 1.4571 - accuracy: 0.5154
Epoch 9/800
17/17 [==============================] - 0s 833us/step - loss: 1.4036 - accuracy: 0.5154
Epoch 10/800
17/17 [==============================] - 0s 833us/step - loss: 1.3559 - accuracy: 0.5192
Epoch 11/80